 2021-09-27 14:12:05.8402|0|INFO|Microsoft.Hosting.Lifetime|Now listening on: https://localhost:5001 |url: |action: | 

 2021-09-27 14:12:05.8643|0|INFO|Microsoft.Hosting.Lifetime|Now listening on: http://localhost:5000 |url: |action: | 

 2021-09-27 14:12:05.8643|0|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down. |url: |action: | 

 2021-09-27 14:12:05.8643|0|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Development |url: |action: | 

 2021-09-27 14:12:05.8643|0|INFO|Microsoft.Hosting.Lifetime|Content root path: C:\Users\admin\source\repos\NLogProductApi\NLogProductApi |url: |action: | 

 2021-09-27 14:12:22.2057|0|ERROR|NLogProductApi.Controllers.ProductController|::1调用了productapi/product/exceptiontest接口返回了失败 System.Exception: 发生了未知的异常
   at NLogProductApi.Controllers.ProductController.ExceptionTest() in C:\Users\admin\source\repos\NLogProductApi\NLogProductApi\Controllers\ProductController.cs:line 23|url: https://localhost/api/Product/exceptiontest|action: ExceptionTest| 

 2021-09-27 14:19:26.0492|0|INFO|Microsoft.Hosting.Lifetime|Now listening on: https://localhost:5001 |url: |action: | 

 2021-09-27 14:19:26.0831|0|INFO|Microsoft.Hosting.Lifetime|Now listening on: http://localhost:5000 |url: |action: | 

 2021-09-27 14:19:26.0831|0|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down. |url: |action: | 

 2021-09-27 14:19:26.0831|0|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Development |url: |action: | 

 2021-09-27 14:19:26.0831|0|INFO|Microsoft.Hosting.Lifetime|Content root path: C:\Users\admin\source\repos\NLogProductApi\NLogProductApi |url: |action: | 

 2021-09-27 14:19:33.0805|1|ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request. System.Exception: 发生了未知的异常
   at NLogProductApi.Controllers.ProductController.ExceptionTest() in C:\Users\admin\source\repos\NLogProductApi\NLogProductApi\Controllers\ProductController.cs:line 21
   at lambda_method2(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)|url: https://localhost/api/Product/exceptiontest|action: ExceptionTest| 

